name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    name: Build, Test, SonarQube & ZAP Scan
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Step 1: Checkout repository
      # ---------------------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for SonarQube scan

      # ---------------------------
      # Step 2: Setup Python
      # ---------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # ---------------------------
      # Step 3: Install dependencies
      # ---------------------------
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest

      # ---------------------------
      # Step 4: Run Unit Tests with Coverage
      # ---------------------------
      - name: Run Unit Tests with Coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          coverage run -m unittest discover -s test -p "*.py"
          coverage xml

      # ---------------------------
      # Step 5: SonarQube Scan
      # ---------------------------
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=Thanusha2003_calc-python
            -Dsonar.organization=thanusha2003
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # ---------------------------
      # Step 6: Build Docker Image
      # ---------------------------
      - name: Build Docker Image
        run: |
          docker build -t calc-python:latest .

      # ---------------------------
      # Step 7: Run Calculator Docker Container
      # ---------------------------
      - name: Run Docker Container
        run: |
          docker run -d --name calc-container -p 5000:5000 calc-python:latest

      # ---------------------------
      # Step 8: OWASP ZAP Baseline Scan
      # ---------------------------
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:5000"
          cmd_options: "-a --autooff -r report_baseline.html"
          allow_issue_writing: false
        env:
          ZAP_AUTH_HEADER: ""
          ZAP_AUTH_HEADER_VALUE: ""
          ZAP_AUTH_HEADER_SITE: ""

      # ---------------------------
      # Step 9: OWASP ZAP Full Scan
      # ---------------------------
      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: "http://localhost:5000"
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          cmd_options: "--autooff -r report_full.html"
          artifact_name: zap_full_scan
          allow_issue_writing: false
          fail_action: false

      # ---------------------------
      # Step 10: Stop Docker Container
      # ---------------------------
      - name: Stop Docker Container
        run: |
          docker stop calc-container
          docker rm calc-container
